// export * from './getArrivalsBoard'
// export * from './getArrivalsBoardWithDetails'
// export * from './getArrivalsDepartureBoard'
// export * from './getArrivalsDepartureBoardWithDetails'
export * from './getDepartureBoard'
// export * from './getDepartureBoardWithDetails'
// export * from './getFastestDeparture'
// export * from './getFastestDepartureWithDetails'
// export * from './getNextDeparture'
// export * from './getNextDepartureWithDetails'
// export * from './getServiceDetails'
